// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("Zipkin.Core")]
[assembly: AssemblyProductAttribute("Zipkin")]
[assembly: AssemblyDescriptionAttribute("A minimalistic .NET client library for Twitter Zipkin tracing.")]
[assembly: InternalsVisibleToAttribute("Zipkin.Core.Tests")]
